#!/usr/bin/env bash
# A script that transfers a file from our client to a server

# the file checks for 4 parameters
  file_path=$1
  server_ip_address=$2
  username=$3
  ssh_key_path=$4

if [ "$#" -ne 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
