#!/usr/bin/env bash
# installs nginx on a new ubuntu machine
# and adds a custom header

# create directory for our html test page
mkdir -p /var/www/html
touch /var/www/html/index.html

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root /var/www/html;
    index index.html index.htm;

    }" > /etc/nginx/sites-available/default

service nginx reload
