#!/usr/bin/env bash
# Bash script that configures a server to run and listen on port 80 of all the server’s active IPv4 IPs
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx reload
sudo service nginx restart
