#!/usr/bin/env bash
# This script is for showcasing the case statement

counter="1"
while [ $counter -le 20 ]
do
	echo "$counter"
	case $counter in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	counter=$((counter+1))
done
